# Generated by Django 3.0.7 on 2020-06-29 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('ts_code', models.CharField(max_length=9, primary_key=True, serialize=False, verbose_name='TS代码')),
                ('symbol', models.CharField(max_length=6, verbose_name='股票代码')),
                ('name', models.CharField(max_length=20, verbose_name='股票名称')),
                ('area', models.CharField(max_length=20, verbose_name='所在地域')),
                ('industry', models.CharField(max_length=20, verbose_name='所属行业')),
                ('list_date', models.DateTimeField(verbose_name='上市日期')),
            ],
        ),
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='分红年度')),
                ('ann_date', models.DateTimeField(blank=True, null=True, verbose_name='预案公告日')),
                ('div_proc', models.CharField(blank=True, max_length=20, null=True, verbose_name='实施进度')),
                ('stk_div', models.FloatField(blank=True, null=True, verbose_name='每股送转')),
                ('stk_bo_rate', models.FloatField(blank=True, null=True, verbose_name='每股送转比例')),
                ('stk_co_rate', models.FloatField(blank=True, null=True, verbose_name='每股转增比例')),
                ('cash_div', models.FloatField(blank=True, null=True, verbose_name='每股分红（税后）')),
                ('cash_div_tax', models.FloatField(blank=True, null=True, verbose_name='每股分红（税前）')),
                ('record_date', models.DateTimeField(blank=True, null=True, verbose_name='股权登记日')),
                ('ex_date', models.DateTimeField(blank=True, null=True, verbose_name='除权登记日')),
                ('pay_date', models.DateTimeField(blank=True, null=True, verbose_name='派息日')),
                ('div_listdate', models.DateTimeField(blank=True, null=True, verbose_name='红股上市日')),
                ('imp_ann_date', models.DateTimeField(blank=True, null=True, verbose_name='实施公告日')),
                ('base_date', models.DateTimeField(blank=True, null=True, verbose_name='基准日')),
                ('base_share', models.FloatField(blank=True, null=True, verbose_name='基准股本（万）')),
                ('ts_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Stock')),
            ],
        ),
        migrations.CreateModel(
            name='DailyBasic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_date', models.DateTimeField(blank=True, null=True, verbose_name='交易日期')),
                ('close', models.FloatField(blank=True, null=True, verbose_name='收盘价')),
                ('turnover_rate', models.FloatField(blank=True, null=True, verbose_name='换手率(%)')),
                ('turnover_rate_f', models.FloatField(blank=True, null=True, verbose_name='换手率(自由流通股)')),
                ('volume_ratio', models.FloatField(blank=True, null=True, verbose_name='量比')),
                ('pe', models.FloatField(blank=True, null=True, verbose_name='市盈率')),
                ('pe_ttm', models.FloatField(blank=True, null=True, verbose_name='市盈率(TTM)')),
                ('pb', models.FloatField(blank=True, null=True, verbose_name='市净率')),
                ('ps', models.FloatField(blank=True, null=True, verbose_name='市销率')),
                ('ps_ttm', models.FloatField(blank=True, null=True, verbose_name='市销率(TTM)')),
                ('dv_ratio', models.FloatField(blank=True, null=True, verbose_name='股息率(%)')),
                ('dv_ttm', models.FloatField(blank=True, null=True, verbose_name='股息率(TTM)')),
                ('total_share', models.FloatField(blank=True, null=True, verbose_name='总股本(万股)')),
                ('float_share', models.FloatField(blank=True, null=True, verbose_name='流通股本(万股)')),
                ('free_share', models.FloatField(blank=True, null=True, verbose_name='自由流通股本(万股)')),
                ('total_mv', models.FloatField(blank=True, null=True, verbose_name='总市值(万元)')),
                ('circ_mv', models.FloatField(blank=True, null=True, verbose_name='流通市值(万元)')),
                ('ts_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Stock')),
            ],
        ),
    ]
